### ISSUE TITLE
Another tweet format

### ISSUE THREAD

**Issue by BLANK-13** [hadysata/KFUPM-semester-progress-bar#1]
### Wouldn't it be better to tweet like this :

 Bar -> just like it is now
 n/130 days 📆  -> this either removed or kept, but I think both are good.
 130 - n  days left⏳  -> adding this line

## Process

TweetHelper () { 

- [ 12] let tweet = ...
- [ 13] tweet += this.newLine('${currentDay} / ${totalSemesterDays} days 📆 ');
- [+14] tweet += this.newLine('${totalSemesterDays - currentDay} days left ⏳');
}

Sorry if something is weird, I never do issues.
I know it's a small change, but I think it would be more exciting to see days left.

**Comment by hadysata** [comment]
Thank you for your suggestion! 🧡
